const name = "Rakib Ahmed"
const address = "shibpur,Narsigndi"
// console.log(`hello i am ${name.toUpperCase()} and ${address.toUpperCase()}`)
const newName = new String ('Rakib Ahmed') ;
const newString = 'test splice'
// console.log(newName.slice(0,3))
// console.log(newName.slice(-11,4))
// console.log(newName.search('d'))
// console.log(newName.search('h'))
// console.log(newName.at('i'))
// console.log(newName.at('a'))
// console.log(newName.at('e'))
// console.log(newName.anchor('ah'))
// console.log(newName.blink('ah'))
// console.log(newName.bold())
// console.log(newName.charAt([0]))
// console.log(newName.charAt([1]))
// console.log(newName.charAt([2]))
// console.log(newName.charAt([3]))
// console.log(newName.charAt([4]))
// console.log(newName.charAt([5]))
// console.log(newName.charAt([6]))
// console.log(newName.charAt([7]))
// console.log(newName.charAt([8]))
// console.log(newName.charAt([9]))
// console.log(newName.charAt([10]))
// console.log(newName.charAt([11]))
// console.log(newName.charAt([12]))
// console.log(newName.charCodeAt([0]))
// console.log(newName.charCodeAt([1]))
// console.log(newName.charCodeAt([2]))
// console.log(newName.charCodeAt([3]))
// console.log(newName.charCodeAt([4]))
// console.log(newName.charCodeAt([5]))
// console.log(newName.charCodeAt([6]))
const icons = new String('☃★♲')
// console.log(icons.codePointAt(2))
// console.log(newName.codePointAt(9))
// console.log(newName.codePointAt(10))
// console.log(newName.concat('a'))
console.log(newName.__proto__)
// console.log(newString.split(''))
// console.log(newName.length)
// console.log(newName__proto__)

const str1 = 'hello '
const str2 = 'bangladesh'
console.log(str1.concat('' , str2))