const setDate = Date()
// console.log(setDate)
// console.log(typeof setDate)
const anotherDate = new Date()
// console.log(anotherDate)
const dateString = Date.toString()
// console.log(dateString)
const dateOne = new Date()
// console.log(dateOne.toString())
// console.log(dateOne.toJSON())
// console.log(dateOne.toISOString())
// console.log(dateOne.toDateString())
// console.log(dateOne.toLocaleDateString())
// console.log(dateOne.toTimeString())
// console.log(dateOne.toUTCString())
// console.log(dateOne.getTimezoneOffset())
// console.log(dateOne.toLocaleString())
const anotherDateTwo = Date.now()

// console.log(dateOne.getDate())
// console.log(dateOne.getDay())
// console.log(dateOne.getFullYear())
// console.log(dateOne.getHours())
// console.log(dateOne.getMilliseconds())
// console.log(dateOne.getMinutes())
// console.log(dateOne.getMonth())
// console.log(dateOne.getSeconds())
// console.log(dateOne.getTime())
// console.log(dateOne.getTimezoneOffset(-100))
// console.log(dateOne.getUTCDate())
// console.log(dateOne.getUTCDay())
// console.log(dateOne.getTime("3-1-2024"))
const anotehr = Date.now()
// console.log(Math.floor(anotehr/1000))
const newDate = new Date()
const newDateResult = newDate.toLocaleString("default",{
    weekday:"long",
    
})
console.log(newDateResult)
